# Usa una imagen de Nginx para servir los archivos HTML
FROM nginx:alpine

# Copia los archivos HTML y CSS al directorio de Nginx
COPY . /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80
